### ISSUE TITLE
Modules Frontend Component

### ISSUE THREAD

**Issue by Anshul-Birla** [TritonSE/LAP-Student-Tracker#101]
![image](https://user-images.githubusercontent.com/42627151/170811736-f4410acb-3f0e-42a2-8316-bfccfae53bcc.png)
^ here is the image of the view to create 

In order to get a sense of the API routes, take a look at #30 . It has a good overview of how to post and add modules and what they contain (items) into the database. Adding a module and item shouldnt be too bad - both just require interacting with some POST routes. 

However, the best way to go about this is probably creating a component called `Module` that renders the dropdown and all the items within it. Within the modules component, you can make a call to the backend to get all the links that belong within that module. This component should also handle the adding, deleting, and editing of the individual items. Creating an item should just have a pop up that looks like the create module pop up, but with name and link instead. The API does not have support to editing modules, so if you could add that in, that would be great. Should just be a PATCH to `/api/module/[module_id]/item/[item_id]` with the following at the body:
```
type EditItem = {
title?: string, 
link?: string 
}
```

Finally, make sure this modules parameter takes in some prop called `enableEditing`. Only allow editing functions to appear when this is set to `true`

In the overall page, we can make a call to `GET /api/class/[id]/modules
` to get all the modules that belong to that class. Then, simply render the `Modules` components in the order specified. 

We can add the ability to move a module up and down. As soon as someone asks a module to move up, we can fire off a call to the database with the new order. We can do this by having an array of moudle id’s in the order they are currently being displayed, and having a function that edits the order when one of the move up/down buttons are called. Make sure to keep track of the fact that the topmost module can’t move up and the bottom most module cant move down (maybe have a min/max that you check).

**Comment by nishantbalaji** [comment]
note: 
make editing a popup
