### ISSUE TITLE
 Search and Filter for all students/class/admin view

### ISSUE THREAD

**Issue by Anshul-Birla** [TritonSE/LAP-Student-Tracker#40]
So this is going to first require some refactoring of the Events API. Now that the class table is created, we need to get the level that a teacher teaches at. First, we need to modify the staff API. 

Create a new user type called `Staff`. `Staff` should just append to `User` object with level and language. Level is a number[] and is nullable, and language is a string []  and nullable 

Query the database by first performing an inner join on the event_information table with the classes table on the event_information_d. Lets call the resulting table x. Then, perform an inner join with the commitments table with table x (on the event_information_id). Lets call this table y.  Finally, perform an outer join on the users table with y on the user_id. and select the correct users. This way, we have a table where if the user has a class, all the class information is filled out, but if they do not, it is a null when it is returned. 

As far as returning the correct users, you will have to do some processing on the data being returned from the db. The processing you need to do is map all the user_id to the class level they teach (so use the `Map` data structure) and the user_id to all the languages they teach. Remember, if they are not a teacher, we do not put them in this map. Once this is done, we go through each user returned and fill out the level field with all the levels that this teacher teaches. Remember if a teacher teaches level 1-3, they teach level 1,2 and 3, so the array should be [1,2,3]. Languages work the same way. If the user is a staff, we simply put null for both things. 

For the frontend:

The way we need to do this is set up 3 states in the `ClassView` component. 
- searchBox (which should be a string), which takes in the input from the search box 
- orderBy (which should be of the 3 types you can order by), which holds the order by vallue 
- selectedClassLevels (which should be a type Set<number>) which holds all the things the user has filtered by. 

Setting up the searchbox is easy  - just get the input from the search box and update the state
The order by isn't too bad either - convert the order by part in the component into a radio button, and update the state based on what is clicked 
selectedClassLevels is a bit more difficult. The checkboxes are made in line 42 (with the `.map` function).  Every time a checkbox is checked (or unchecked), we need to call a function that updates the set in the `selectedClassLevels` state (if a input box has been checked, you add the level to the state. If it has been unchecked, you remove the level). Each checkbox should get a value passed in (that is the level the checbox represents) so you can easily access it when the event fires. 

The filtering is the easy part. Check if the search query given is contained in the first and last name of a given element and/or check any of the level's they teach are part of the `selectedClassLevels`. If these are true, keep them, else throw them out. `.filter()` is your best bet here. For the order by stuff, just make a custom sorting function that can sort how each order by is supposed to be sorted, and you should be good to go. 

The component `ClassScroll` should take in these values and filter by them.

**Comment by nishantbalaji** [comment]
- get route for staff should return levels array (all the levels that teacher is assigned) and languages that teacher teaches --> query classes teacher is assigned to 
   -  `left join`
   - put into set then turn into array
   - some sort of computations to get all langs and min level and max level that a teacher teaches
-
